---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 and php packages package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"


  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: remove apache2 and php package
    dnf:
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"