---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php package
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS"